[package]
name = "nkd-w4"
version = "0.0.0"
edition = "2021"
license = "BSD-3-Clause"
authors = ["Avery R. <contact@nekodjin.org>"]

[dependencies]
buddy-alloc = "0.4.1"
nkd-w4-prim = { version = "0.0.0", path = "../nkd-w4-prim" }
spin = "0.9.4"
