[package]
name = "nkd-w4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
buddy-alloc = "0.4.1"
nkd-w4-prim = { version = "0.0.0", path = "../nkd-w4-prim" }
spin = "0.9.4"
